// Seed de plantillas de mensajes — extraídas del prompt actual del agente IA (post-restructuración)
// Formato: k=key (para el placeholder {{tpl:key}} en el prompt), s=section, sl=section_label,
// so=section_order, io=item_order, t=title, c=context, m=message
const TEMPLATES = [
  { k:'saludo-inicial', s:'saludo', sl:'Saludo e inicio', so:1, io:1,
    t:'Saludo inicial',
    c:'Primer mensaje con el que arrancás cualquier conversación nueva.',
    m:'Buenas! Cómo andas?' },
  { k:'sena-oferta-directa', s:'sena', sl:'Seña', so:2, io:1,
    t:'Oferta directa de seña (con motivo y condiciones)',
    c:'Mensaje directo al ofrecer la seña: explica por qué conviene señar y las condiciones (se descuenta del valor, no se devuelve, 7 días de validez, monto fijo).',
    m:'Mirá, nosotros trabajamos con señas porque muchas veces tenemos solo uno o dos equipos de este tipo, y como respondemos 24/7, puede pasar que si no lo señás, se venda antes de que vengas.\nLa seña son $[seña] — se descuenta del valor final del equipo. Es un compromiso de compra: no se devuelve, pero si en el momento preferís otro equipo, se te deja a favor para ese. Tiene 7 días de validez.\n¿Te copa dejarla así lo aseguramos con tu nombre?' },
  { k:'sena-rechazada', s:'sena', sl:'Seña', so:2, io:2,
    t:'Cliente no quiere dejar seña',
    c:'Se anota el turno igual, sin presionar.',
    m:'Dale, perfecto! Anotamos el turno igual. El equipo sigue disponible, cualquier cosa avisá.' },
  { k:'sena-aceptada-alias', s:'sena', sl:'Seña', so:2, io:3,
    t:'Cliente acepta la seña — alias',
    c:'Mensaje con el alias de transferencia, una vez aceptada la seña.',
    m:'Transferís $[seña] al alias altechreserva26, a nombre de Jazmin. Cuando tengas el comprobante me avisás — y decime a nombre de quién va a llegar así lo registramos. 📲' },
  { k:'ofrecer-cargador', s:'accesorios', sl:'Accesorios', so:3, io:1,
    t:'Ofrecer cargador (reactivo)',
    c:'Se ofrece SOLO si el cliente menciona espontáneamente que no tiene cargador.',
    m:'Te conviene llevar uno certificado — te sale $[cargador] extra. ¿Querés que te lo sume?' },
  { k:'pregunta-metodo-pago', s:'pago', sl:'Método de pago', so:4, io:1,
    t:'Pregunta de método de pago',
    c:'Se pregunta directo cómo prefiere pagar, sin asumir financiación.',
    m:'¿Cómo preferís pagar los $[saldo]?\n- Efectivo (pesos o dólares)\n- Transferencia en pesos\n- Tarjeta de crédito en cuotas\n- Crédito personal con DNI' },
  { k:'pregunta-cuotas', s:'pago', sl:'Método de pago', so:4, io:2,
    t:'Pregunta de cuotas',
    c:'Cuando el cliente elige tarjeta.',
    m:'¿En cuántas cuotas?\n- 1 cuota (+12% de recargo)\n- 3 cuotas (+35% de recargo)\n- 6 cuotas (+50% de recargo)\n- 12 cuotas (+92% de recargo)' },
  { k:'pago-pesos-alias', s:'pago', sl:'Método de pago', so:4, io:3,
    t:'Pago en pesos — total y alias',
    c:'Mensaje obligatorio antes de dar el alias cuando paga en pesos.',
    m:'Bárbaro [nombre]. El equipo te queda en $[USD] USD, que en pesos son $[total pesos] pesos.\nTransferís al alias altech.mp a nombre de Matías Ganzero.\nUna vez que hagas la transferencia mandame una imagen del comprobante y te agendamos el turno. ¿A nombre de quién lo anotamos?' },
  { k:'no-tarjeta-naranja', s:'pago', sl:'Método de pago', so:4, io:4,
    t:'No aceptamos Tarjeta Naranja',
    c:'Respuesta cuando preguntan por Tarjeta Naranja.',
    m:'Tarjeta Naranja no la aceptamos. Sí aceptamos cualquier otra tarjeta de crédito en hasta 12 cuotas, transferencia, efectivo o crédito personal con el DNI. ¿Tenés alguna de esas?' },
  { k:'no-mercado-pago', s:'pago', sl:'Método de pago', so:4, io:5,
    t:'No aceptamos Mercado Pago',
    c:'Respuesta cuando preguntan por Mercado Pago.',
    m:'Mercado Pago no lo aceptamos, pero podés pagar con tarjeta de crédito en hasta 12 cuotas, transferencia en pesos, o crédito personal con el DNI. ¿Cuál te viene mejor?' },
  { k:'credito-no-apto', s:'pago', sl:'Método de pago', so:4, io:6,
    t:'¿Qué pasa si no soy apto para crédito personal?',
    c:'Respuesta tranquilizadora, ofreciendo alternativas.',
    m:'Casi siempre que sí! Pero en el caso de que no, te avisamos y buscamos juntos otra solución — menos cuotas en tarjeta, más adelanto, o un equipo más accesible. No te quedás sin opciones.' },
  { k:'credito-veraz', s:'pago', sl:'Método de pago', so:4, io:7,
    t:'Cliente en Veraz / con deuda',
    c:'Corte directo del crédito personal, sin pedir CUIL.',
    m:'Entiendo. Lamentablemente en esa situación no podemos otorgar el crédito personal. Podemos ver otras opciones — más cuotas en tarjeta, o un equipo más accesible. ¿Cómo lo ves?' },
  { k:'credito-sin-recibo', s:'pago', sl:'Método de pago', so:4, io:8,
    t:'Cliente sin recibo de sueldo',
    c:'Se deriva para que lo evalúen en el local, nunca se rechaza directamente.',
    m:'Eso lo tienen que evaluar directamente en el local — te van a estar contactando para ver las opciones.' },
  { k:'pedir-cuil', s:'pago', sl:'Método de pago', so:4, io:9,
    t:'Pedir CUIL para crédito personal',
    c:'Paso previo a la verificación de aptitud crediticia.',
    m:'Barbaro. Vamos a pasar tu CUIL al local para verificar si estás apto — te van a estar contactando.' },
  { k:'cotizacion-canje-formato', s:'canje', sl:'Canje de usados', so:6, io:1,
    t:'Formato de cotización de canje',
    c:'Mensaje con el valor de toma, siempre sin daños (cualquier daño deriva antes).',
    m:'Tu [modelo] de [GB]GB con [batería]% de batería, hoy cotiza en $[valor] USD.\nEn el local lo van a chequear — si está todo ok como decís, ese es el valor.\nSi tiene rayones muy leves, se chequea pero no se suele bajar — entendemos que es un equipo usado.' },
  { k:'cierre-canje-aplicado', s:'canje', sl:'Canje de usados', so:6, io:2,
    t:'Cierre con canje aplicado',
    c:'Desglose final cuando el canje se descuenta del equipo nuevo.',
    m:'El [nuevo] de $[precio] menos $[canje] por tu [viejo] = $[total] USD a pagar. ¿Cómo lo ves?' },
  { k:'derivar-reparaciones-msg', s:'canje', sl:'Canje de usados', so:6, io:3,
    t:'Derivación por reparaciones',
    c:'Mensaje exacto cuando se deriva por reparación (canje con daño, o consulta directa).',
    m:'Este número es de ventas — lo de reparaciones lo manejan aparte. Te van a contactar desde el local para darte el valor, o si preferís ya podés escribirles directo al 2914614009.' },
  { k:'comparar-bateria-vs-canje', s:'canje', sl:'Canje de usados', so:6, io:4,
    t:'Comparar cambiar batería vs entregar el equipo',
    c:'Con los dos valores reales (costo de batería aprox. y diferencia de canje), para que el cliente decida. No deriva en este paso.',
    m:'Cambiar la batería te sale aproximadamente $100 USD.\\nPero si entregás tu [modelo actual] en parte de pago por el [modelo nuevo], la diferencia te queda en $[precio nuevo - valor canje] USD, y tendrías un equipo mejor con la batería al 100%.\\n¿Cómo lo ves?' },
  { k:'garantia-original-l17', s:'garantia', sl:'Garantía', so:7, io:1,
    t:'Garantía — batería original, línea 17',
    c:'Solo línea 17 se llama "semi nuevos".',
    m:'(Semi nuevos en caja, con garantía oficial Apple, todas sus piezas originales)' },
  { k:'garantia-original-otras', s:'garantia', sl:'Garantía', so:7, io:2,
    t:'Garantía — batería original, otras líneas',
    c:'Cualquier línea que no sea 17 se llama "usados", no "semi nuevos".',
    m:'(Usados, con garantía oficial Apple, todas sus piezas originales)' },
  { k:'garantia-cambiada-nosotros', s:'garantia', sl:'Garantía', so:7, io:3,
    t:'Garantía — batería cambiada por nosotros',
    c:'X se reemplaza por el warranty_months real del sub-agente.',
    m:'(Batería original cambiada por nosotros, con [X] meses de garantía)' },
  { k:'garantia-cambiada-tercero', s:'garantia', sl:'Garantía', so:7, io:4,
    t:'Garantía — batería cambiada por un tercero',
    c:'Nunca decir "garantía oficial Apple" acá.',
    m:'(Batería cambiada por un tercero — no es pieza original y no la garantiza Apple — con [X] meses de garantía nuestra)' },
  { k:'faq-esperar-local', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:1,
    t:'¿Puedo quedarme esperando?',
    c:'No se puede quedar esperando el traspaso en el local.',
    m:'Nono, la idea es que no te quedes esperando — tenemos varios turnos para atender y el espacio en la oficina es reducido.\nTe tomamos los datos de contacto y te vamos avisando por acá cómo va el traspaso y cuándo está listo.' },
  { k:'faq-demora-traspaso', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:2,
    t:'¿Qué demora tiene el traspaso?',
    c:'Nunca decir "20 a 40 minutos" — la demora real es más larga.',
    m:'El traspaso demora entre 1 y 2 horas, depende de cuánta información tenga el equipo — fotos, apps, todo eso.\nPor eso no hace falta que esperes en el local, te avisamos apenas está listo.' },
  { k:'proteccion-robo-mensaje', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:3,
    t:'Explicar protección contra robo',
    c:'Obligatorio explicar esto antes o al coordinar el turno.',
    m:'Importante antes de venir: tenés que desactivar la protección en caso de robo desde tu iPhone, así podemos hacer el traspaso sin problema.\n¿Te acordás tu contraseña de iCloud? La vas a necesitar en el momento.' },
  { k:'ofrecer-instructivo', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:4,
    t:'Ofrecer el instructivo',
    c:'Cuando el cliente no sabe si tiene la protección activada.',
    m:'Dale, ¿querés que te pase un instructivo así vemos si está desactivada? Así podemos adelantar unos pasos.' },
  { k:'instructivo-proteccion-robo', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:5,
    t:'Instructivo completo de protección contra robo',
    c:'Mensaje largo, se manda completo sin dividir.',
    m:'🔐 Importante – Equipo en parte de pago\nPara poder realizar la transferencia y el traspaso de datos, necesitamos que verifiques una opción en tu iPhone:\n\n1️⃣ Entrá en Ajustes > Face ID y código\n2️⃣ Ingresá tu código\n3️⃣ Buscá la opción "Protección en caso de robo"\n\n👉 Si está DESACTIVADA, perfecto, no hace falta hacer nada más.\n👉 Si está ACTIVADA, seguí estos pasos:\n- Entrá en la opción y desactivala\n- El iPhone te va a avisar que hay un período de espera\n- Tocá "Iniciar período de espera"\n- Tenés que estar atent@ aproximadamente 1 hora (en algunos casos se desactiva antes)\n\n4️⃣ Cuando el sistema avise que el período finalizó:\n- Entrá nuevamente\n- Volvé a desactivar la protección\n- Te va a pedir Face ID\n- Confirmá que quede desactivada\n\n✅ Con esto ya podemos:\n- Restablecer la contraseña de iCloud si es necesario\n- Hacer el traspaso de datos\n- Evitar que el sistema pida sí o sí tu Face ID durante el proceso\n\nGracias por hacerlo antes de venir, así hacemos todo más rápido y sin demoras 🙌' },
  { k:'obj-muy-caro', s:'objeciones', sl:'Objeciones', so:9, io:1,
    t:'"Es muy caro"',
    c:'Entender si es presupuesto o valor percibido.',
    m:'¿Es más el tema presupuesto o te parece que no vale la pena?' },
  { k:'obj-dolar-caro', s:'objeciones', sl:'Objeciones', so:9, io:2,
    t:'"Ese dólar está muy caro"',
    c:'Explicar la cotización de la financiera.',
    m:'Entiendo que te parezca caro. Nosotros trabajamos con una financiera que nos vende a ese valor.\nSi vos preferís comprar los dólares por tu cuenta, también podés pagarnos directo en USD.' },
  { k:'obj-mas-barato-otro-lado', s:'objeciones', sl:'Objeciones', so:9, io:3,
    t:'"Lo vi más barato en otro lado"',
    c:'Preguntar dónde antes de responder.',
    m:'¿Dónde lo viste?' },
  { k:'obj-mercadolibre', s:'objeciones', sl:'Objeciones', so:9, io:4,
    t:'"Lo vi en MercadoLibre más barato"',
    c:'Diferenciar por la garantía y verificación en persona.',
    m:'En Meli hay de todo jaja. El problema es que no podés verificar antes de comprar, no sabés si la batería es real o si tiene piezas cambiadas.\nAcá venís, lo probás, chequeamos la batería en el momento, y si algo falla dentro de la garantía volvés. Ese es el valor.' },
  { k:'obj-no-actualizan', s:'objeciones', sl:'Objeciones', so:9, io:5,
    t:'"No lo actualizan / es viejo"',
    c:'Desmentir con datos reales de soporte de iOS.',
    m:'Eso es un mito.\nAcaba de salir iOS 18 y Apple ya confirmó el 19 y 20. Mínimo 3-4 años más de updates.\n¿Qué uso buscabas darle?' },
  { k:'obj-esperar-nuevo', s:'objeciones', sl:'Objeciones', so:9, io:6,
    t:'"Prefiero esperar al modelo nuevo"',
    c:'Argumento de amortización con canje.',
    m:'Dale, es tu decisión.\nPero los modelos más nuevos ya están, y el que tenés en mente hoy ya bajó bastante de precio.\nSi comprás ahora con tu equipo en canje, lo amortizás rápido. ¿Cómo lo ves?' },
  { k:'obj-quiero-sellado', s:'objeciones', sl:'Objeciones', so:9, io:7,
    t:'"Quiero uno nuevo/sellado"',
    c:'Entender el motivo real detrás del pedido.',
    m:'¿Lo buscás nuevo por garantía o porque te gusta que sea sin abrir?' },
  { k:'obj-no-confio-usados', s:'objeciones', sl:'Objeciones', so:9, io:8,
    t:'"No confío en los usados"',
    c:'Argumento de garantía real, con la comparación de la Ferrari.',
    m:'Comprarlo usado no importa tanto si lo comprás en un lugar con garantía real.\nEs como comprar una Ferrari usada — la calidad no cambia.\ntodos los equipos que vendemos son testeados y con garantía' },
  { k:'obj-bateria-verdad', s:'objeciones', sl:'Objeciones', so:9, io:9,
    t:'"¿Cómo sé que la batería es verdad?"',
    c:'Se verifica en persona, en el momento.',
    m:'Cuando venís lo vemos en Settings > Battery Health, vos mismo, en el momento. Nada de capturas ni fotos.' },
  { k:'obj-que-pasa-si-se-dana', s:'objeciones', sl:'Objeciones', so:9, io:10,
    t:'"¿Qué pasa si se daña?"',
    c:'Garantía oficial Apple, sin excusas.',
    m:'Garantía oficial Apple. Si falla sin culpa tuya, se arregla.\nNuestros clientes vuelven cuando quieren hacer upgrade, no porque se rompió.' },
  { k:'obj-sin-presupuesto', s:'objeciones', sl:'Objeciones', so:9, io:11,
    t:'"No tengo presupuesto ahora"',
    c:'Ofrecer combinación de efectivo + cuotas o crédito personal.',
    m:'No hay drama. Podés combinar efectivo con cuotas, o hacer crédito personal con el DNI.\n¿Cuánto podrías poner ahora y financiamos el resto?' },
  { k:'obj-tarjeta-sin-interes', s:'objeciones', sl:'Objeciones', so:9, io:12,
    t:'"Necesito tarjeta sin interés"',
    c:'Aclarar que todas las cuotas tienen interés, y ofrecer crédito personal.',
    m:'En tarjeta todas las cuotas tienen interés. También está crédito personal — 3 cuotas fijas en USD, solo con el DNI.' },
  { k:'obj-sin-limite-tarjeta', s:'objeciones', sl:'Objeciones', so:9, io:13,
    t:'Cliente sin límite en la tarjeta',
    c:'Ofrecer alternativas: menos cuotas, crédito personal, o equipo más accesible.',
    m:'Nono hay drama. Podés hacer menos cuotas para que baje el monto, usar crédito personal con el DNI, o mirar un equipo un poco más accesible. ¿Cuál te cierra más?' },
  { k:'insiste-precio', s:'casos_especiales', sl:'Casos especiales', so:10, io:1,
    t:'Cliente insiste solo en el precio',
    c:'Se da el precio pero igual se pregunta el uso.',
    m:'El [modelo] arranca en $[precio] USD. ¿Para qué lo buscás? Así te recomiendo el que más te conviene.' },
  { k:'pide-fotos', s:'casos_especiales', sl:'Casos especiales', so:10, io:2,
    t:'Cliente pide fotos del equipo',
    c:'El bot no puede mandar fotos, se ofrece verlo en persona.',
    m:'Las fotos las tienen en el local — te las pueden mandar directamente. De todas formas cuando venís lo ves, lo probás y chequeamos todo en el momento. ¿Querés que te agendemos un turno?' },
  { k:'comparar-modelos', s:'casos_especiales', sl:'Casos especiales', so:10, io:3,
    t:'Comparar dos modelos',
    c:'Resumen breve de la diferencia entre dos opciones.',
    m:'Para lo que me dijiste, el [modelo A] te da [ventaja]. El [modelo B] es más accesible. ¿Querés que te muestre los dos?' },
  { k:'mismo-modelo', s:'casos_especiales', sl:'Casos especiales', so:10, io:4,
    t:'Cliente quiere el mismo modelo que ya tiene',
    c:'Preguntar el motivo antes de mostrar nada.',
    m:'¿Lo buscás para reemplazarlo por alguna razón? ¿Rotura, más almacenamiento, cambio de color?' },
  { k:'cambiar-por-rotura', s:'casos_especiales', sl:'Casos especiales', so:10, io:5,
    t:'Cliente quiere cambiar por rotura',
    c:'Ofrecer la reparación como alternativa antes de vender.',
    m:'Si es por rotura, quizás conviene verlo primero en el local — a veces la reparación sale mucho menos. ¿Qué tiene?' },
  { k:'derivar-accesorios-msg', s:'casos_especiales', sl:'Casos especiales', so:10, io:6,
    t:'Derivación por accesorios/otros productos',
    c:'AirPods, Mac, iPad, Apple Watch — se deriva al local.',
    m:'Eso lo manejan directo en el local — te van a estar contactando.' },
  { k:'regalo-inicio', s:'casos_especiales', sl:'Casos especiales', so:10, io:7,
    t:'Compra de regalo — inicio',
    c:'Preguntas iniciales apuntando al destinatario.',
    m:'Qué bueno! ¿Cuántos años tiene? ¿Usa iPhone actualmente o sería su primer iPhone?' },
  { k:'regalo-cierre', s:'casos_especiales', sl:'Casos especiales', so:10, io:8,
    t:'Compra de regalo — cierre',
    c:'Cuando ya eligieron el equipo para el regalo.',
    m:'Genial, el [modelo] es una excelente elección para regalo. ¿Querés pasar a verlo o lo coordinamos con turno?' },
  { k:'precio-en-pesos', s:'casos_especiales', sl:'Casos especiales', so:10, io:9,
    t:'Precio en pesos',
    c:'Conversión sin mencionar la cotización salvo que la pidan.',
    m:'Te lo paso en pesos! El [modelo] sale $[USD] USD, que en pesos son $[total] pesos aprox — la cotización varía día a día.' },
  { k:'viene-de-anuncio', s:'casos_especiales', sl:'Casos especiales', so:10, io:10,
    t:'Cliente viene de un anuncio',
    c:'Ya eligió el producto, se va directo sin el checklist completo.',
    m:'Sisi lo tenemos!\n¿Es para vos? ¿Venís de iPhone o de otro celular?' },
];

module.exports = TEMPLATES;