// Seed de plantillas de mensajes — extraídas del prompt actual del agente IA (post-restructuración)
// Formato: k=key (para el placeholder {{tpl:key}} en el prompt), s=section, sl=section_label,
// so=section_order, io=item_order, t=title, c=context, m=message
const TEMPLATES = [
  { k:'saludo-inicial', s:'saludo', sl:'Saludo e inicio', so:1, io:1,
    t:'Saludo inicial',
    c:'Primer mensaje con el que arrancás cualquier conversación nueva.',
    m:'Buenas! Cómo andas?' },
  { k:'sena-oferta-directa', s:'sena', sl:'Seña', so:2, io:1,
    t:'Oferta directa de seña (con motivo y condiciones)',
    c:'Mensaje directo al ofrecer la seña: explica por qué conviene señar y las condiciones (se descuenta del valor, no se devuelve, 7 días de validez, monto fijo).',
    m:'Mirá, nosotros trabajamos con señas porque muchas veces tenemos solo uno o dos equipos de este tipo, y como respondemos 24/7, puede pasar que si no lo señás, se venda antes de que vengas.\nLa seña son $[seña] — se descuenta del valor final del equipo. Es un compromiso de compra: no se devuelve, pero si en el momento preferís otro equipo, se te deja a favor para ese. Tiene 7 días de validez.\n¿Te copa dejarla así lo aseguramos con tu nombre?' },
  { k:'sena-rechazada', s:'sena', sl:'Seña', so:2, io:2,
    t:'Cliente no quiere dejar seña',
    c:'Se anota el turno igual, sin presionar.',
    m:'Dale, perfecto! Anotamos el turno igual. El equipo sigue disponible, cualquier cosa avisá.' },
  { k:'sena-aceptada-alias', s:'sena', sl:'Seña', so:2, io:3,
    t:'Cliente acepta la seña — alias',
    c:'Mensaje con el alias de transferencia, una vez aceptada la seña.',
    m:'Transferís $[seña] al alias altechreserva26, a nombre de Jazmin. Cuando tengas el comprobante me avisás — y decime a nombre de quién va a llegar así lo registramos. 📲' },
  { k:'ofrecer-cargador', s:'accesorios', sl:'Accesorios', so:3, io:1,
    t:'Ofrecer cargador (reactivo)',
    c:'Se ofrece SOLO si el cliente menciona espontáneamente que no tiene cargador.',
    m:'Te conviene llevar uno certificado — te sale $[cargador] extra. ¿Querés que te lo sume?' },
  { k:'pregunta-metodo-pago', s:'pago', sl:'Método de pago', so:4, io:1,
    t:'Pregunta de método de pago',
    c:'Se pregunta directo cómo prefiere pagar, sin asumir financiación.',
    m:'¿Cómo preferís pagar los $[saldo]?\n- Efectivo (pesos o dólares)\n- Transferencia en pesos\n- Tarjeta de crédito en cuotas\n- Crédito personal con DNI' },
  { k:'pregunta-cuotas', s:'pago', sl:'Método de pago', so:4, io:2,
    t:'Pregunta de cuotas',
    c:'Cuando el cliente elige tarjeta.',
    m:'¿En cuántas cuotas?\n- 1 cuota (+12% de recargo)\n- 3 cuotas (+35% de recargo)\n- 6 cuotas (+50% de recargo)\n- 12 cuotas (+92% de recargo)' },
  { k:'aviso-cuenta-dni', s:'pago', sl:'Método de pago', so:4, io:9,
    t:'Aviso Cuenta DNI — revisar límite diario',
    c:'Se avisa cuando el cliente menciona específicamente Cuenta DNI, ya que a veces el límite diario de transferencia es bajo.',
    m:'Dale, con Cuenta DNI también podés transferir sin problema — eso sí, revisá tu límite diario antes de venir, a veces viene bajo y no entra el monto completo en una sola transferencia.' },
  { k:'info-usdt-cripto', s:'pago', sl:'Método de pago', so:4, io:10,
    t:'Info USDT / cripto (3% de comisión)',
    c:'Se explica cuando el cliente pregunta por pagar en cripto — el 3% se calcula siempre real, nunca aproximado.',
    m:'Sisi, aceptamos USDT. Se cobra un 3% de comisión arriba del valor en USD del equipo. Por ejemplo, a $1000 USD serían $1030 USDT.' },
  { k:'credito-personal-explicacion', s:'pago', sl:'Método de pago', so:4, io:11,
    t:'Crédito personal — explicación general del modelo financiero',
    c:'Mensaje base que se manda SIEMPRE al elegir crédito personal, antes de calcular el número real del caso puntual del cliente. Contiene sus propios ejemplos ilustrativos fijos (no reemplazar por el caso real acá, el cálculo real va en un mensaje aparte).',
    m:'El crédito personal se hace mediante un contrato, donde la persona se compromete a pagar 3 cuotas fijas en USD.\n👉 Si las cuotas no se pagan, el equipo se da de baja de manera remota y deja de funcionar.\n\nLas cuotas pueden pagarse en pesos, a la cotización de nuestra financiera el día del pago (del 1 al 10 de cada mes).\n\n📍 Financiamos hasta $400 USD.\nPor ejemplo:\n– Si financiás $400 USD, las 3 cuotas quedan en $200 USD cada una (interés incluido), unos $[cuota_200_pesos] pesos cada una a la cotización de hoy.\n\nSi no entregás un equipo en forma de pago, necesitás hacer una entrega mínima de $100 USD.\nEjemplo:\n– Querés un iPhone de $400 USD\n– Entregás $100 USD\n– El resto ($300 USD) se financia en 3 cuotas de $150 USD, unos $[cuota_150_pesos] pesos cada una a la cotización de hoy.' },
  { k:'credito-personal-resultado', s:'pago', sl:'Método de pago', so:4, io:14,
    t:'Crédito personal — resultado del caso real del cliente',
    c:'Se manda después de la explicación general, con el número real del caso. Las cuotas SIEMPRE llevan su equivalente en pesos (cuota USD × cotización de hoy). [entrega] = entrega mínima en USD, [cuota] = cuota en USD.',
    m:'Para este equipo la entrega mínima es de $[entrega] USD, y te quedan 3 cuotas fijas de $[cuota] USD cada una (hoy serían unos $[cuota en pesos] pesos cada una; se pagan en pesos a la cotización de la financiera el día del pago).' },
  { k:'pago-pesos-derivar', s:'pago', sl:'Método de pago', so:4, io:3,
    t:'Pago en pesos — total y derivación (ya no hay alias propio para esto)',
    c:'Mensaje cuando el cliente paga el equipo completo en pesos. Ya no se da ningún alias directo — se deriva para que el local lo pase.',
    m:'Bárbaro [nombre]. El equipo te queda en $[USD] USD, que en pesos son $[total pesos] pesos.\nTe paso con el local para que te pasen el alias y coordinemos ahí la transferencia.' },
  { k:'no-tarjeta-naranja', s:'pago', sl:'Método de pago', so:4, io:4,
    t:'No aceptamos Tarjeta Naranja',
    c:'Respuesta cuando preguntan por Tarjeta Naranja.',
    m:'Tarjeta Naranja no la aceptamos. Sí aceptamos cualquier otra tarjeta de crédito en hasta 12 cuotas, transferencia, efectivo o crédito personal con el DNI. ¿Tenés alguna de esas?' },
  { k:'no-mercado-pago', s:'pago', sl:'Método de pago', so:4, io:5,
    t:'No aceptamos Mercado Pago',
    c:'Respuesta cuando preguntan por Mercado Pago.',
    m:'Mercado Pago no lo aceptamos, pero podés pagar con tarjeta de crédito en hasta 12 cuotas, transferencia en pesos, o crédito personal con el DNI. ¿Cuál te viene mejor?' },
  { k:'credito-no-apto', s:'pago', sl:'Método de pago', so:4, io:6,
    t:'¿Qué pasa si no soy apto para crédito personal?',
    c:'Respuesta tranquilizadora, ofreciendo alternativas.',
    m:'Casi siempre que sí! Pero en el caso de que no, te avisamos y buscamos juntos otra solución — menos cuotas en tarjeta, más adelanto, o un equipo más accesible. No te quedás sin opciones.' },
  { k:'credito-veraz', s:'pago', sl:'Método de pago', so:4, io:7,
    t:'Cliente en Veraz / con deuda',
    c:'Corte directo del crédito personal, sin pedir documentos.',
    m:'Entiendo. Lamentablemente en esa situación no podemos otorgar el crédito personal. Podemos ver otras opciones — más cuotas en tarjeta, o un equipo más accesible. ¿Cómo lo ves?' },
  { k:'pedir-documentos-credito', s:'pago', sl:'Método de pago', so:4, io:8,
    t:'Pedir documentos para crédito personal (y derivar)',
    c:'Se pide en el mismo mensaje donde se deriva — CUIL + recibo de sueldo, o monotributo + comprobante/garante.',
    m:'Para el crédito personal necesitamos tu CUIL y una foto de tu recibo de sueldo. Si tenés monotributo, mandame la constancia de monotributo junto con un comprobante de ingresos, o si preferís, un garante. Con eso, los chicos del local lo revisan directamente y te dicen si estás apto.' },
  { k:'cotizacion-canje-formato', s:'canje', sl:'Canje de usados', so:6, io:1,
    t:'Formato de cotización de canje',
    c:'Mensaje con el valor de toma, siempre sin daños (cualquier daño deriva antes, excepto un rayón).',
    m:'Tu [modelo] de [GB]GB con [batería]% de batería, hoy cotiza en $[valor] USD.\nEn el local lo van a chequear — si está todo ok como decís, ese es el valor.\nSi tiene rayones muy leves, se chequea pero no se suele bajar — entendemos que es un equipo usado.' },
  { k:'cierre-canje-aplicado', s:'canje', sl:'Canje de usados', so:6, io:2,
    t:'Cierre con canje aplicado',
    c:'Desglose final cuando el canje se descuenta del equipo nuevo.',
    m:'El [nuevo] de $[precio] menos $[canje] por tu [viejo] = $[total] USD a pagar. ¿Cómo lo ves?' },
  { k:'derivar-reparaciones-msg', s:'canje', sl:'Canje de usados', so:6, io:3,
    t:'Derivación por reparaciones (consulta directa, con teléfono)',
    c:'Mensaje exacto cuando el cliente pregunta directamente por reparar su equipo (no canje). El cliente se comunica él mismo con el sector de reparaciones — nunca decir que alguien lo va a contactar.',
    m:'Este número es solo de ventas, las reparaciones las maneja otro sector.\nComunicate directo con ellos al 2914614009 y ahí te dan precio y tiempos.' },
  { k:'derivar-canje-con-dano-msg', s:'canje', sl:'Canje de usados', so:6, io:4,
    t:'Derivación por canje con daño (sin teléfono de reparaciones)',
    c:'Mensaje exacto cuando se deriva un canje porque el equipo tiene un daño (no un rayón) — nunca menciona el teléfono de reparaciones, ese es solo para consultas de reparación.',
    m:'Eso lo tienen que ver directamente en el local para poder darte un valor exacto — te van a estar contactando.' },
  { k:'garantia-original-l17', s:'garantia', sl:'Garantía', so:7, io:1,
    t:'Garantía — batería original, línea 17',
    c:'Línea 17 de mostrador (no sellados): semi nuevos, sin caja. [X] = equipment_warranty_months real, normalmente 3. Sin garantía oficial Apple.',
    m:'(Semi nuevos de mostrador, sin caja, con todas sus piezas originales, con [X] meses de garantía)' },
  { k:'garantia-original-otras', s:'garantia', sl:'Garantía', so:7, io:2,
    t:'Garantía — batería original, otras líneas',
    c:'Cualquier modelo con batería original que no sea 17, premium ni sellado se llama "usados". [X] = equipment_warranty_months real, normalmente 3. Sin garantía oficial Apple.',
    m:'(Usados, con todas sus piezas originales, con [X] meses de garantía)' },
  { k:'garantia-cambiada-nosotros', s:'garantia', sl:'Garantía', so:7, io:3,
    t:'Garantía — batería cambiada por nosotros',
    c:'[X] = equipment_warranty_months real (garantía del equipo, normalmente 12). [Y] = warranty_months real (garantía de la batería sola, normalmente 3).',
    m:'(Batería original cambiada por nosotros, con [X] meses de garantía en el equipo y [Y] meses en la batería)' },
  { k:'garantia-cambiada-tercero', s:'garantia', sl:'Garantía', so:7, io:4,
    t:'Garantía — batería cambiada por un tercero',
    c:'Nunca decir "garantía oficial Apple" acá.',
    m:'(Batería cambiada por un tercero — no es pieza original y no la garantiza Apple — con [X] meses de garantía nuestra)' },
  { k:'faq-esperar-local', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:1,
    t:'¿Puedo quedarme esperando?',
    c:'No se puede quedar esperando el traspaso en el local.',
    m:'Nono, la idea es que no te quedes esperando — tenemos varios turnos para atender y el espacio en la oficina es reducido.\nTe tomamos los datos de contacto y te vamos avisando por acá cómo va el traspaso y cuándo está listo.' },
  { k:'faq-demora-traspaso', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:2,
    t:'¿Qué demora tiene el traspaso?',
    c:'Nunca decir "20 a 40 minutos" — la demora real es más larga.',
    m:'El traspaso demora entre 1 y 2 horas, depende de cuánta información tenga el equipo — fotos, apps, todo eso.\nPor eso no hace falta que esperes en el local, te avisamos apenas está listo.' },
  { k:'proteccion-robo-mensaje', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:3,
    t:'Explicar protección contra robo',
    c:'Obligatorio explicar esto antes o al coordinar el turno.',
    m:'Importante antes de venir: tenés que desactivar la protección en caso de robo desde tu iPhone, así podemos hacer el traspaso sin problema.\n¿Te acordás tu contraseña de iCloud? La vas a necesitar en el momento.' },
  { k:'ofrecer-instructivo', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:4,
    t:'Ofrecer el instructivo',
    c:'Cuando el cliente no sabe si tiene la protección activada.',
    m:'Dale, ¿querés que te pase un instructivo así vemos si está desactivada? Así podemos adelantar unos pasos.' },
  { k:'instructivo-proteccion-robo', s:'faq_visita', sl:'Preguntas frecuentes — visita', so:8, io:5,
    t:'Instructivo completo de protección contra robo',
    c:'Mensaje largo, se manda completo sin dividir.',
    m:'🔐 Importante – Equipo en parte de pago\nPara poder realizar la transferencia y el traspaso de datos, necesitamos que verifiques una opción en tu iPhone:\n\n1️⃣ Entrá en Ajustes > Face ID y código\n2️⃣ Ingresá tu código\n3️⃣ Buscá la opción "Protección en caso de robo"\n\n👉 Si está DESACTIVADA, perfecto, no hace falta hacer nada más.\n👉 Si está ACTIVADA, seguí estos pasos:\n- Entrá en la opción y desactivala\n- El iPhone te va a avisar que hay un período de espera\n- Tocá "Iniciar período de espera"\n- Tenés que estar atent@ aproximadamente 1 hora (en algunos casos se desactiva antes)\n\n4️⃣ Cuando el sistema avise que el período finalizó:\n- Entrá nuevamente\n- Volvé a desactivar la protección\n- Te va a pedir Face ID\n- Confirmá que quede desactivada\n\n✅ Con esto ya podemos:\n- Restablecer la contraseña de iCloud si es necesario\n- Hacer el traspaso de datos\n- Evitar que el sistema pida sí o sí tu Face ID durante el proceso\n\nGracias por hacerlo antes de venir, así hacemos todo más rápido y sin demoras 🙌' },
  { k:'obj-muy-caro', s:'objeciones', sl:'Objeciones', so:9, io:1,
    t:'"Es muy caro"',
    c:'Entender si es presupuesto o valor percibido.',
    m:'¿Es más el tema presupuesto o te parece que no vale la pena?' },
  { k:'obj-dolar-caro', s:'objeciones', sl:'Objeciones', so:9, io:2,
    t:'"Ese dólar está muy caro"',
    c:'Explicar la cotización de la financiera.',
    m:'Entiendo que te parezca caro. Nosotros trabajamos con una financiera que nos vende a ese valor.\nSi vos preferís comprar los dólares por tu cuenta, también podés pagarnos directo en USD.' },
  { k:'obj-mas-barato-otro-lado', s:'objeciones', sl:'Objeciones', so:9, io:3,
    t:'"Lo vi más barato en otro lado"',
    c:'Preguntar dónde antes de responder.',
    m:'¿Dónde lo viste?' },
  { k:'obj-mercadolibre', s:'objeciones', sl:'Objeciones', so:9, io:4,
    t:'"Lo vi en MercadoLibre más barato"',
    c:'Diferenciar por la garantía y verificación en persona.',
    m:'En Meli hay de todo jaja. El problema es que no podés verificar antes de comprar, no sabés si la batería es real o si tiene piezas cambiadas.\nAcá venís, lo probás, chequeamos la batería en el momento, y si algo falla dentro de la garantía volvés. Ese es el valor.' },
  { k:'obj-no-actualizan', s:'objeciones', sl:'Objeciones', so:9, io:5,
    t:'"No lo actualizan / es viejo"',
    c:'Desmentir con datos reales de soporte de iOS.',
    m:'Eso es un mito.\nAcaba de salir iOS 18 y Apple ya confirmó el 19 y 20. Mínimo 3-4 años más de updates.\n¿Qué uso buscabas darle?' },
  { k:'obj-esperar-nuevo', s:'objeciones', sl:'Objeciones', so:9, io:6,
    t:'"Prefiero esperar al modelo nuevo"',
    c:'Argumento de amortización con canje.',
    m:'Dale, es tu decisión.\nPero los modelos más nuevos ya están, y el que tenés en mente hoy ya bajó bastante de precio.\nSi comprás ahora con tu equipo en canje, lo amortizás rápido. ¿Cómo lo ves?' },
  { k:'obj-quiero-sellado', s:'objeciones', sl:'Objeciones', so:9, io:7,
    t:'"Quiero uno nuevo/sellado"',
    c:'Entender el motivo real detrás del pedido.',
    m:'¿Lo buscás nuevo por garantía o porque te gusta que sea sin abrir?' },
  { k:'obj-no-confio-usados', s:'objeciones', sl:'Objeciones', so:9, io:8,
    t:'"No confío en los usados"',
    c:'Argumento de garantía real, con la comparación de la Ferrari.',
    m:'Comprarlo usado no importa tanto si lo comprás en un lugar con garantía real.\nEs como comprar una Ferrari usada — la calidad no cambia.\ntodos los equipos que vendemos son testeados y con garantía' },
  { k:'obj-bateria-verdad', s:'objeciones', sl:'Objeciones', so:9, io:9,
    t:'"¿Cómo sé que la batería es verdad?"',
    c:'Se verifica en persona, en el momento.',
    m:'Cuando venís lo vemos en Settings > Battery Health, vos mismo, en el momento. Nada de capturas ni fotos.' },
  { k:'obj-que-pasa-si-se-dana', s:'objeciones', sl:'Objeciones', so:9, io:10,
    t:'"¿Qué pasa si se daña?"',
    c:'Garantía escrita de 3 meses en todos los equipos; los sellados suman 12 meses de garantía oficial Apple.',
    m:'Tenés garantía escrita de 3 meses. Si falla sin culpa tuya, se arregla.\nY si es un sellado, además tenés 12 meses de garantía oficial de Apple.\nNuestros clientes vuelven cuando quieren hacer upgrade, no porque se rompió.' },
  { k:'obj-sin-presupuesto', s:'objeciones', sl:'Objeciones', so:9, io:11,
    t:'"No tengo presupuesto ahora"',
    c:'Ofrecer combinación de efectivo + cuotas o crédito personal.',
    m:'No hay drama. Podés combinar efectivo con cuotas, o hacer crédito personal con el DNI.\n¿Cuánto podrías poner ahora y financiamos el resto?' },
  { k:'obj-tarjeta-sin-interes', s:'objeciones', sl:'Objeciones', so:9, io:12,
    t:'"Necesito tarjeta sin interés"',
    c:'Aclarar que todas las cuotas tienen interés, y ofrecer crédito personal.',
    m:'En tarjeta todas las cuotas tienen interés. También está crédito personal — 3 cuotas fijas en USD, solo con el DNI.' },
  { k:'obj-sin-limite-tarjeta', s:'objeciones', sl:'Objeciones', so:9, io:13,
    t:'Cliente sin límite en la tarjeta',
    c:'Ofrecer alternativas: menos cuotas, crédito personal, o equipo más accesible.',
    m:'Nono hay drama. Podés hacer menos cuotas para que baje el monto, usar crédito personal con el DNI, o mirar un equipo un poco más accesible. ¿Cuál te cierra más?' },
  { k:'pide-fotos', s:'casos_especiales', sl:'Casos especiales', so:10, io:2,
    t:'Cliente pide fotos del equipo',
    c:'El bot no puede mandar fotos, se ofrece verlo en persona.',
    m:'Las fotos las tienen en el local — te las pueden mandar directamente. De todas formas cuando venís lo ves, lo probás y chequeamos todo en el momento. ¿Querés que te agendemos un turno?' },
  { k:'comparar-modelos', s:'casos_especiales', sl:'Casos especiales', so:10, io:3,
    t:'Comparar dos modelos',
    c:'Resumen breve de la diferencia entre dos opciones.',
    m:'Para lo que me dijiste, el [modelo A] te da [ventaja]. El [modelo B] es más accesible. ¿Querés que te muestre los dos?' },
  { k:'mismo-modelo', s:'casos_especiales', sl:'Casos especiales', so:10, io:4,
    t:'Cliente quiere el mismo modelo que ya tiene',
    c:'Preguntar el motivo antes de mostrar nada.',
    m:'¿Lo buscás para reemplazarlo por alguna razón? ¿Rotura, más almacenamiento, cambio de color?' },
  { k:'cambiar-por-rotura', s:'casos_especiales', sl:'Casos especiales', so:10, io:5,
    t:'Cliente quiere cambiar por rotura',
    c:'Ofrecer la reparación como alternativa antes de vender.',
    m:'Si es por rotura, quizás conviene verlo primero en el local — a veces la reparación sale mucho menos. ¿Qué tiene?' },
  { k:'derivar-accesorios-msg', s:'casos_especiales', sl:'Casos especiales', so:10, io:6,
    t:'Derivación por accesorios/otros productos',
    c:'AirPods, Mac, iPad, Apple Watch — se deriva al local.',
    m:'Eso lo manejan directo en el local — te van a estar contactando.' },
  { k:'regalo-inicio', s:'casos_especiales', sl:'Casos especiales', so:10, io:7,
    t:'Compra de regalo — inicio',
    c:'Preguntas iniciales apuntando al destinatario.',
    m:'Qué bueno! ¿Cuántos años tiene? ¿Usa iPhone actualmente o sería su primer iPhone?' },
  { k:'regalo-cierre', s:'casos_especiales', sl:'Casos especiales', so:10, io:8,
    t:'Compra de regalo — cierre',
    c:'Cuando ya eligieron el equipo para el regalo.',
    m:'Genial, el [modelo] es una excelente elección para regalo. ¿Querés pasar a verlo o lo coordinamos con turno?' },
  { k:'precio-en-pesos', s:'casos_especiales', sl:'Casos especiales', so:10, io:9,
    t:'Precio en pesos',
    c:'Conversión sin mencionar la cotización salvo que la pidan.',
    m:'Te lo paso en pesos! El [modelo] sale $[USD] USD, que en pesos son $[total] pesos aprox — la cotización varía día a día.' },
  { k:'viene-de-anuncio', s:'casos_especiales', sl:'Casos especiales', so:10, io:10,
    t:'Cliente viene de un anuncio',
    c:'Ya eligió el producto, se va directo sin el checklist completo.',
    m:'Sisi lo tenemos!\n¿Es para vos? ¿Venís de iPhone o de otro celular?' },
  { k:'modelo-sin-stock', s:'oferta', sl:'Oferta de productos', so:11, io:1,
    t:'Modelo exacto sin stock',
    c:'Primer mensaje cuando el modelo pedido no está en stock, antes de ofrecer alternativas.',
    m:'Justo el [modelo exacto] no lo tenemos en stock.' },
  { k:'pregunta-detalle-canje', s:'canje', sl:'Canje de usados', so:6, io:5,
    t:'Pregunta 2 del canje — detalle del equipo',
    c:'Pregunta obligatoria después de GB+batería, para saber si hay algún daño.',
    m:'¿Tiene algún detalle? Pantalla rota, tapa trasera, Face ID que no funcione, o pantalla cambiada por módulo no original?' },
  { k:'resumen-primer-iphone', s:'canje', sl:'Canje de usados', so:6, io:6,
    t:'Resumen de equipo elegido — primer iPhone',
    c:'Cuando es primer iPhone, cierre simple sin mencionar canje.',
    m:'Barbaro, el [modelo] es una gran elección para empezar!\nTe queda en $[precio] USD +$[cargador si eligió].\n¿Cómo preferís pagar?' },
  { k:'pregunta-primer-iphone-canje', s:'canje', sl:'Canje de usados', so:6, io:7,
    t:'Pregunta de Fase 4 — primer iPhone o canje',
    c:'Pregunta clave apenas el cliente confirma una unidad específica.',
    m:'Contame si es tu primer iPhone o tenés uno para dar en parte de pago.' },
  { k:'desglose-total-ejemplo', s:'pago', sl:'Método de pago', so:4, io:12,
    t:'Desglose del total — ejemplo con equipo + cargador + canje',
    c:'Formato para mostrar siempre de dónde viene cada número del total a pagar.',
    m:'El [modelo] $[precio] USD, menos $[canje] del [equipo entregado] = $[subtotal] USD del equipo.\nEl cargador son $[cargador] pesos ($[cargador ÷ dolar] USD a la cotización de hoy).\nTotal a pagar: $[subtotal] USD del equipo + $[cargador] pesos del cargador. ✅' },
  { k:'cuotas-resultado-simple', s:'pago', sl:'Método de pago', so:4, io:13,
    t:'Resultado de cuotas — mensaje simplificado',
    c:'Nunca se muestra el cálculo paso a paso, solo el resultado final por cuota.',
    m:'Bien, en 3 cuotas con tarjeta te quedaría por abonar 3 cuotas de $[monto] cada una.\nEn 6 cuotas, serían 6 cuotas de $[monto] cada una.\nY en 12 cuotas, 12 cuotas de $[monto] cada una.' },
  { k:'pregunta-horario', s:'reservas_citas', sl:'Reservas y citas', so:12, io:1,
    t:'Pregunta de horario para agendar',
    c:'Primera parte del turno combinado de Fase 6 (horario + seña).',
    m:'¿Cuándo te queda bien venir?' },
  { k:'reprogramar-turno', s:'reservas_citas', sl:'Reservas y citas', so:12, io:2,
    t:'Reprogramar turno — pregunta',
    c:'Cuando el cliente pide cambiar el horario de un turno ya agendado.',
    m:'No hay problema! ¿Para cuándo te queda mejor?' },
  { k:'reprogramar-confirmar', s:'reservas_citas', sl:'Reservas y citas', so:12, io:3,
    t:'Reprogramar turno — confirmación',
    c:'Mensaje de cierre una vez que el cliente dio el nuevo horario.',
    m:'Listo, te moví para el [día] a las [hora]. Te esperamos!' },
  { k:'cancelar-turno', s:'reservas_citas', sl:'Reservas y citas', so:12, io:4,
    t:'Cancelar turno',
    c:'Mensaje cuando el cliente pide cancelar un turno ya agendado.',
    m:'Dale, cancelamos el turno. Si en algún momento querés volver, avisanos. Y si dejaste seña, coordinalo con el local.' },
  { k:'garantia-premium', s:'garantia', sl:'Garantía', so:7, io:5,
    t:'Garantía — Calidad Premium (11 / 13 mini / 13 / 13 Pro / 13 Pro Max)',
    c:'Solo para esos modelos con batería original: nuevos con la caja abierta. [X] = equipment_warranty_months real, normalmente 3.',
    m:'(Nuevos con caja abierta, con cable original y sin piezas cambiadas, con [X] meses de garantía)' },
  { k:'garantia-sellado', s:'garantia', sl:'Garantía', so:7, io:6,
    t:'Garantía — sellados (17 / 17 Pro / 17 Pro Max / 18 Pro / 18 Pro Max)',
    c:'Los sellados NO llevan la etiqueta Calidad Premium. [X] = equipment_warranty_months real, normalmente 3. Los 12 meses de garantía oficial Apple son solo de sellados.',
    m:'(Sellado, con el cable en la caja, [X] meses de garantía nuestra y 12 meses de garantía oficial Apple)' },
  { k:'sena-a-pedido-oferta', s:'sena', sl:'Seña', so:2, io:4,
    t:'Seña de producto a pedido — oferta (sin turno)',
    c:'Para equipos a pedido: se ofrece la seña para pedirlo. No se agenda turno.',
    m:'Este equipo lo traemos a pedido, así que para pedirlo necesitamos una seña de $[seña]. Es un compromiso de compra: se descuenta del valor final del equipo, no se devuelve y tiene 7 días de validez.\n¿Lo señamos así lo pedimos para vos?' },
  { k:'sena-a-pedido-alias', s:'sena', sl:'Seña', so:2, io:5,
    t:'Seña de producto a pedido — alias (sin turno)',
    c:'Alias de seña para un producto a pedido. No se coordina horario.',
    m:'Dale! Transferís $[seña] al alias altechreserva26, a nombre de Jazmin. Cuando tengas el comprobante me lo mandás, y los chicos del local te van a estar hablando para avisarte cuando esté para retirar.' },
  { k:'a-pedido-sena-recibida', s:'sena', sl:'Seña', so:2, io:6,
    t:'Seña de producto a pedido — recibida (se deriva)',
    c:'Se envía junto con Derivar cuando el sistema detecta el comprobante de seña de un producto a pedido.',
    m:'Listo, recibimos tu seña! Los chicos del local te van a estar hablando para avisarte cuando esté para retirar.' },
  { k:'horario-fuera-de-rango', s:'reservas_citas', sl:'Reservas y citas', so:12, io:5,
    t:'Horario fuera de la atención',
    c:'Antes de la apertura, después del cierre, o domingo.',
    m:'Trabajamos de lunes a viernes de 11 a 18 hs y sábados de 10 a 15 hs. ¿Te queda bien algún horario dentro de esos?' },
  { k:'horario-pasado-tope', s:'reservas_citas', sl:'Reservas y citas', so:12, io:6,
    t:'Horario pasado el último turno del día',
    c:'Dentro de la atención pero demasiado cerca del cierre. [último horario] lo calcula Ampi según el día y si hay canje.',
    m:'Ese día el último horario que puedo darte es a las [último horario]. ¿Te queda bien alguno antes de esa hora?' },
  { k:'horario-ocupado', s:'reservas_citas', sl:'Reservas y citas', so:12, io:7,
    t:'Horario ya ocupado por otro turno',
    c:'Hay otro turno agendado en ese horario (con o sin seña). Se ofrece el libre más cercano.',
    m:'Ese horario ya lo tengo ocupado. ¿Te queda bien a las [horario libre más cercano]?' },
  { k:'condicion-no-disponible', s:'oferta', sl:'Oferta de productos', so:11, io:2,
    t:'Lo que pidió el cliente no existe (se ofrece lo más cercano)',
    c:'Cuando el cliente pidió una condición (ej: sellado / nuevo de caja) y no hay unidad que la cumpla. Se dice directo y recién después se ofrece lo más cercano con su nombre real. Ej: "El 13 sellado no lo manejamos. Lo más parecido que tengo es Calidad Premium, que son nuevos con la caja abierta, con cable original y sin piezas cambiadas."',
    m:'El [modelo] [lo que pidió] no lo manejamos.\nLo más parecido que tengo es [lo que hay, con su nombre real], que es [explicación corta de qué es].' },
];

module.exports = TEMPLATES;